name: Evangelie Zachos
baseurl: "/"
url: "https://ezachos.github.io" 
theme: null

plugins:
    - jekyll-sitemap

defaults:
    -
        scope:
            path: "blog"
            type: "posts"
        values:
            layout: "blog"
            
paginate: 10
paginate_path: "/blog/page:num"